name: Maturin

on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: aarch64
          manylinux: 2_28
          args: --release --out dist
      - uses: uraimo/run-on-arch-action@v3
        name: Install built wheel
        with:
          arch: aarch64
          distro: ubuntu20.04
          install: |
            apt-get update
            apt-get install -y --no-install-recommends python3 python3-pip
            pip3 install -U pip
          run: |
            pip3 install uv --no-index --find-links dist/ --force-reinstall
            pip install pytest
            pytest -v
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
